
package mtlStub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RemoteCenterServerMTLImplService", targetNamespace = "http://centerServers", wsdlLocation = "http://localhost:8080/A3-COMP6231/services/RemoteCenterServerMTLImpl?wsdl")
public class RemoteCenterServerMTLImplService
    extends Service
{

    private final static URL REMOTECENTERSERVERMTLIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException REMOTECENTERSERVERMTLIMPLSERVICE_EXCEPTION;
    private final static QName REMOTECENTERSERVERMTLIMPLSERVICE_QNAME = new QName("http://centerServers", "RemoteCenterServerMTLImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/A3-COMP6231/services/RemoteCenterServerMTLImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REMOTECENTERSERVERMTLIMPLSERVICE_WSDL_LOCATION = url;
        REMOTECENTERSERVERMTLIMPLSERVICE_EXCEPTION = e;
    }

    public RemoteCenterServerMTLImplService() {
        super(__getWsdlLocation(), REMOTECENTERSERVERMTLIMPLSERVICE_QNAME);
    }

    public RemoteCenterServerMTLImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REMOTECENTERSERVERMTLIMPLSERVICE_QNAME, features);
    }

    public RemoteCenterServerMTLImplService(URL wsdlLocation) {
        super(wsdlLocation, REMOTECENTERSERVERMTLIMPLSERVICE_QNAME);
    }

    public RemoteCenterServerMTLImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REMOTECENTERSERVERMTLIMPLSERVICE_QNAME, features);
    }

    public RemoteCenterServerMTLImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RemoteCenterServerMTLImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RemoteCenterServerMTLImpl
     */
    @WebEndpoint(name = "RemoteCenterServerMTLImpl")
    public RemoteCenterServerMTLImpl getRemoteCenterServerMTLImpl() {
        return super.getPort(new QName("http://centerServers", "RemoteCenterServerMTLImpl"), RemoteCenterServerMTLImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RemoteCenterServerMTLImpl
     */
    @WebEndpoint(name = "RemoteCenterServerMTLImpl")
    public RemoteCenterServerMTLImpl getRemoteCenterServerMTLImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://centerServers", "RemoteCenterServerMTLImpl"), RemoteCenterServerMTLImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REMOTECENTERSERVERMTLIMPLSERVICE_EXCEPTION!= null) {
            throw REMOTECENTERSERVERMTLIMPLSERVICE_EXCEPTION;
        }
        return REMOTECENTERSERVERMTLIMPLSERVICE_WSDL_LOCATION;
    }

}
