
package ddoStub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RemoteCenterServerDDOImplService", targetNamespace = "http://centerServers", wsdlLocation = "http://localhost:8080/A3-COMP6231/services/RemoteCenterServerDDOImpl?wsdl")
public class RemoteCenterServerDDOImplService
    extends Service
{

    private final static URL REMOTECENTERSERVERDDOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException REMOTECENTERSERVERDDOIMPLSERVICE_EXCEPTION;
    private final static QName REMOTECENTERSERVERDDOIMPLSERVICE_QNAME = new QName("http://centerServers", "RemoteCenterServerDDOImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/A3-COMP6231/services/RemoteCenterServerDDOImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REMOTECENTERSERVERDDOIMPLSERVICE_WSDL_LOCATION = url;
        REMOTECENTERSERVERDDOIMPLSERVICE_EXCEPTION = e;
    }

    public RemoteCenterServerDDOImplService() {
        super(__getWsdlLocation(), REMOTECENTERSERVERDDOIMPLSERVICE_QNAME);
    }

    public RemoteCenterServerDDOImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REMOTECENTERSERVERDDOIMPLSERVICE_QNAME, features);
    }

    public RemoteCenterServerDDOImplService(URL wsdlLocation) {
        super(wsdlLocation, REMOTECENTERSERVERDDOIMPLSERVICE_QNAME);
    }

    public RemoteCenterServerDDOImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REMOTECENTERSERVERDDOIMPLSERVICE_QNAME, features);
    }

    public RemoteCenterServerDDOImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RemoteCenterServerDDOImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RemoteCenterServerDDOImpl
     */
    @WebEndpoint(name = "RemoteCenterServerDDOImpl")
    public RemoteCenterServerDDOImpl getRemoteCenterServerDDOImpl() {
        return super.getPort(new QName("http://centerServers", "RemoteCenterServerDDOImpl"), RemoteCenterServerDDOImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RemoteCenterServerDDOImpl
     */
    @WebEndpoint(name = "RemoteCenterServerDDOImpl")
    public RemoteCenterServerDDOImpl getRemoteCenterServerDDOImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://centerServers", "RemoteCenterServerDDOImpl"), RemoteCenterServerDDOImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REMOTECENTERSERVERDDOIMPLSERVICE_EXCEPTION!= null) {
            throw REMOTECENTERSERVERDDOIMPLSERVICE_EXCEPTION;
        }
        return REMOTECENTERSERVERDDOIMPLSERVICE_WSDL_LOCATION;
    }

}
