
package lvlStub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RemoteCenterServerLVLImplService", targetNamespace = "http://centerServers", wsdlLocation = "http://localhost:8080/A3-COMP6231/services/RemoteCenterServerLVLImpl?wsdl")
public class RemoteCenterServerLVLImplService
    extends Service
{

    private final static URL REMOTECENTERSERVERLVLIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException REMOTECENTERSERVERLVLIMPLSERVICE_EXCEPTION;
    private final static QName REMOTECENTERSERVERLVLIMPLSERVICE_QNAME = new QName("http://centerServers", "RemoteCenterServerLVLImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/A3-COMP6231/services/RemoteCenterServerLVLImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REMOTECENTERSERVERLVLIMPLSERVICE_WSDL_LOCATION = url;
        REMOTECENTERSERVERLVLIMPLSERVICE_EXCEPTION = e;
    }

    public RemoteCenterServerLVLImplService() {
        super(__getWsdlLocation(), REMOTECENTERSERVERLVLIMPLSERVICE_QNAME);
    }

    public RemoteCenterServerLVLImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REMOTECENTERSERVERLVLIMPLSERVICE_QNAME, features);
    }

    public RemoteCenterServerLVLImplService(URL wsdlLocation) {
        super(wsdlLocation, REMOTECENTERSERVERLVLIMPLSERVICE_QNAME);
    }

    public RemoteCenterServerLVLImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REMOTECENTERSERVERLVLIMPLSERVICE_QNAME, features);
    }

    public RemoteCenterServerLVLImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RemoteCenterServerLVLImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RemoteCenterServerLVLImpl
     */
    @WebEndpoint(name = "RemoteCenterServerLVLImpl")
    public RemoteCenterServerLVLImpl getRemoteCenterServerLVLImpl() {
        return super.getPort(new QName("http://centerServers", "RemoteCenterServerLVLImpl"), RemoteCenterServerLVLImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RemoteCenterServerLVLImpl
     */
    @WebEndpoint(name = "RemoteCenterServerLVLImpl")
    public RemoteCenterServerLVLImpl getRemoteCenterServerLVLImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://centerServers", "RemoteCenterServerLVLImpl"), RemoteCenterServerLVLImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REMOTECENTERSERVERLVLIMPLSERVICE_EXCEPTION!= null) {
            throw REMOTECENTERSERVERLVLIMPLSERVICE_EXCEPTION;
        }
        return REMOTECENTERSERVERLVLIMPLSERVICE_WSDL_LOCATION;
    }

}
